/*
 *                 Sun Public License Notice
 * 
 * The contents of this file are subject to the Sun Public License
 * Version 1.0 (the "License"). You may not use this file except in
 * compliance with the License. A copy of the License is available at
 * http://www.sun.com/
 * 
 * The Original Code is Forte for Java, Community Edition. The Initial
 * Developer of the Original Code is Sun Microsystems, Inc. Portions
 * Copyright 1997-2000 Sun Microsystems, Inc. All Rights Reserved.
 */

package org.netbeans.modules.search;

import java.beans.*;

/**
 * Show customizer of underlayed criterion.
 *
 * @author  Petr Kuzel
 * @version 
 */
public class CriterionView extends javax.swing.JPanel {

    private CriterionModel model;

    /** Creates new form CriterionTab */
    public CriterionView(CriterionModel model) {

        this.model = model;

        initComponents ();

        PresetView presetPanel = new PresetView(model.getPresetModel());

        // obtain tab label string & icon TODO
        setName(model.getName());

        // create one tab
        add(model.getComponent(), "Center"); // NOI18N
        add(presetPanel, "North" ); // NOI18N

        setBorder (new javax.swing.border.EmptyBorder(new java.awt.Insets(4, 4, 4, 4)));

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents () {//GEN-BEGIN:initComponents
        setLayout (new java.awt.BorderLayout ());

    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}


/*
* Log
*  5    Gandalf   1.4         1/13/00  Radko Najman    I18N
*  4    Gandalf   1.3         1/10/00  Petr Kuzel      Buttons enabling.
*  3    Gandalf   1.2         1/5/00   Petr Kuzel      Margins used. Help 
*       contexts.
*  2    Gandalf   1.1         1/4/00   Petr Kuzel      Bug hunting.
*  1    Gandalf   1.0         12/23/99 Petr Kuzel      
* $ 
*/ 

