/*
 *                 Sun Public License Notice
 * 
 * The contents of this file are subject to the Sun Public License
 * Version 1.0 (the "License"). You may not use this file except in
 * compliance with the License. A copy of the License is available at
 * http://www.sun.com/
 * 
 * The Original Code is Forte for Java, Community Edition. The Initial
 * Developer of the Original Code is Sun Microsystems, Inc. Portions
 * Copyright 1997-2000 Sun Microsystems, Inc. All Rights Reserved.
 */

package org.netbeans.modules.debugger.support;

import org.openide.util.NbBundle;


/**
 *
 * @author  jjancura
 * @version 
 */
public class StopActionPanel extends javax.swing.JPanel {

    static final long serialVersionUID =6035632320515312585L;

    private StopAction action;

    /** Creates new form StopActionPanel */
    public StopActionPanel(StopAction action) {
        this.action = action;
        initComponents ();
        jCheckBox1.setSelected (action.getStop ());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents () {//GEN-BEGIN:initComponents
        jCheckBox1 = new javax.swing.JCheckBox ();
        setLayout (new java.awt.FlowLayout (0, 0, 0));

        jCheckBox1.setText (NbBundle.getBundle (PrintActionPanel.class).getString ("CTL_Stop_debugging"));
        jCheckBox1.addActionListener (new java.awt.event.ActionListener () {
                                          public void actionPerformed (java.awt.event.ActionEvent evt) {
                                              jCheckBox1ActionPerformed (evt);
                                          }
                                      }
                                     );


        add (jCheckBox1);

    }//GEN-END:initComponents

    private void jCheckBox1ActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // Add your handling code here:
        action.setStop (jCheckBox1.isSelected ());
    }//GEN-LAST:event_jCheckBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    // End of variables declaration//GEN-END:variables

}
/*
 * Log
 *  3    Gandalf   1.2         11/5/99  Jan Jancura     Add Breakpoint Dialog 
 *       design updated
 *  2    Gandalf   1.1         10/23/99 Ian Formanek    NO SEMANTIC CHANGE - Sun
 *       Microsystems Copyright in File Comment
 *  1    Gandalf   1.0         9/2/99   Jan Jancura     
 * $
 */
